### ISSUE TITLE
Private repo

### ISSUE THREAD

**Issue by timozattol** [SimonCommits/miniKernel#1]
Careful, I asked the OS teacher not too long ago, he said we should not make the code of the OS assignments public :(

**Comment by SimonCommits** [comment]
haha I got you(almost 1st of april)!! It's actually the mini-kernel we built with Concurrency class with Schiper

**Comment by timozattol** [comment]
Damn it! Can't nazi people peacefully those days... haha :P Sorry

**Comment by SimonCommits** [comment]
<3 jerry golay
